### ISSUE TITLE
Non-MMIO interrupt-controller nodes are illegal

### ISSUE THREAD

**Issue by konradybcio** [devicetree-org/dt-schema#104]
Currently, [/schemas/interrupt-controller.yaml](https://github.com/devicetree-org/dt-schema/blob/main/dtschema/schemas/interrupt-controller.yaml) allows the node names to match:

`"^interrupt-controller(@[0-9a-f,]+)*$"`

Which means that for non-MMIO-mapped nodes we can only use `interrupt-controller`.

But then, a property with an identical name (`interrupt-controller;`) is required.

Trying to create such a node emits a warning in dtc:

`Warning (node_name_vs_property_name): /example-0/interrupt-controller: node name and property name conflict`

**Comment by robherring** [comment]
Our choices are relax the naming (with "interrupt-controller-[0-9]+") or rework the example template causing this. I don't think the pattern (having both interrupt-controller as node and property) is likely in a real DT, so I'm going with the latter. I have a fix I'm testing now.
