### ISSUE TITLE
License and PyPi release

### ISSUE THREAD

**Issue by sorki** [devicetree-org/dt-schema#35]
Hi,
the license of the project is not clear (would be nice if it had a `LICENSE` file). 

If you publish this on PyPi it would make packaging easier as well.

**Comment by robherring** [comment]
Every file has an SPDX tag.

**Comment by sorki** [comment]
Oh, never mind then, PyPi release would be nice though.

**Comment by robherring** [comment]
Yeah, PyPi releases are on my todo. I've delayed it as the project has been evolving rather quickly and you pretty much need to be using the tip. But hopefully things are starting to mature a bit.

**Comment by sorki** [comment]
No problem, take your time, I will use the GitHub repo directly meanwhile and update when available.

Since the package builds correctly with `setup.py` it should be just a matter of `python setup.py sdist upload` and proper configuration of PyPi access (and registration).

**Comment by robherring** [comment]
Uploaded to PyPI: https://pypi.org/project/dtschema/2020.6rc1/

Should resolve #41 too.
